### ISSUE TITLE
Add Gemfiles for each of Rails 2.3, 3.0, 3.1 and 3.2

### ISSUE THREAD

**Issue by alindeman** [alindeman/zonebie#1]
And make them run against Travis: http://about.travis-ci.org/docs/user/languages/ruby/ "Custom Bundler arguments and Gemfile locations"

**Comment by odlp** [comment]
There's a gem called [appraisal](https://github.com/thoughtbot/appraisal) which is helpful for generating Gemfiles with different versions of dependencies. Would you be interested in a PR to add this?

**Comment by alindeman** [comment]
> There's a gem called appraisal which is helpful for generating Gemfiles with different versions of dependencies. Would you be interested in a PR to add this?

@odlp Sure!
