### ISSUE TITLE
Limit timezones for a specific country or group of zones?

### ISSUE THREAD

**Issue by statique** [alindeman/zonebie#6]
Is it possible to provide a list of countries or timezones to focus the tests? I realize that timezone logic should work for any timezone, but the test suite "feels" weird having it test locations that the application was not designed to service.

It would be nice if one could pass a configuration block to Zonebie that includes a list of acceptable timezones and/or a list of countries that are supported."

**Comment by vemv** [comment]
> but the test suite "feels" weird having it test locations that the application was not designed to service.

Then ensure you don't have any timezone-related bugs, so you don't feel this 'weirdness' :)

Limiting the timezones is a dangerous path - it makes it less likely to find bugs, giving you a potentialy false sense of confidence.

**Comment by alindeman** [comment]
Agreed.

**Comment by TildeWilliams** [comment]
I was just looking for this feature since my app is only available in the US.
