### ISSUE TITLE
Traveling around the world

### ISSUE THREAD

**Issue by r38y** [alindeman/zonebie#9]
I don't know about anybody else, but I feel like I'm traveling around the world every time I run my tests. This is great!

I was wondering if it would be worth including the first paragraph from wikipedia for each timezone so you can learn a bit while waiting for your tests to run. 

For example, for Krasnoyarsk, we would pull the first paragraph (all above TOC) from http://en.wikipedia.org/wiki/Krasnoyarsk:

> Krasnoyarsk (Russian: Красноярск, IPA: [krəsnɐˈjærsk]) is a city and the administrative center of Krasnoyarsk Krai, Russia, located on the Yenisei River. It is the third largest city in Siberia after Novosibirsk and Omsk, with a population of 973,826 (2010 Census).[8] Krasnoyarsk is an important junction of the Trans-Siberian Railway and one of Russia's largest producers of aluminium.

> The city is notable for its nature landscapes; author Anton Chekhov judged Krasnoyarsk to be the most beautiful city in Siberia.[13]

I don't know, thought this might be kind of cool. I don't know how we would do it in an efficient manner. Maybe a second gem that just has these for each timezone? I'd hate to pull it down on every test run.

**Comment by tpbowden** [comment]
Check out #11 and let me know what you think please

**Comment by alindeman** [comment]
This is a pretty neat idea, but I think I'm going to bias towards keeping the `zonebie` gem small and focused. If anyone wants to take a stab at adding hooks or lightweight plugins to `zonebie` so a hypothetical `zonebie-travel` or `zonebie-wikipedia` (e.g.) gem could provide this functionality, I think I'd gladly accept that.

**Comment by tpbowden** [comment]
I have just extracted #11 into a gem called [zonebie-info](https://github.com/tpbowden/zonebie-info). Zonebie was already easily extendable without any extra work

**Comment by alindeman** [comment]
> I have just extracted #11 into a gem called zonebie-info. Zonebie was already easily extendable without any extra work

Awesome :sparkles:
